
# 浏览器驱动配置信息
# 浏览器驱动信息，驱动下载页：https://sites.google.com/a/chromium.org/chromedriver/downloads
# 也可以参考这里：http://www.testclass.net/selenium_python/selenium3-browser-driver/
driver:
  # 浏览器驱动名称， 如：
  # 谷歌：Chrome
  # 火狐：firefox
  # 苹果：Safari
  # 欧朋：opera
  # Edge：edge
  # 别问我为啥没有IE, 这个问题你自己想吧。。。。
  name: 'chrome'
  # 浏览器驱动路径
  path: 'E:\\Projects\\chromedriver.exe'



# 配置文件请严格按照yaml语法格式书写
info:
  # 账号密码为空时采用二维码登录
  # 鉴于验证码识别不便，建议扫描二维码登录
  12306account: ''
  password: ''

  # 时间间隔，单位：秒   可为浮点数，如：1.2表示1.2秒
  # 程序加载网页的时间间隔, 在网络不良或者12306网站反应迟钝时可适当增大刷票时间间隔
  # 可根据具体需要自行改变程序等待时间间隔， 程序中所有 “self.interval” 均引用此变量
  interval: 1.2

  # 出发城市， 如：上海
  from_station: '上海'

  # 到达城市， 如： 南京
  to_station: '南京'

  # 出发日期， 格式：- '2019-04-21'
  start_date: '2019-05-24'

  # 车次， 填写需要购买的车次，越靠前优先级越高，格式：
  # - 'G3985'
  # - 'C2221'
  # - 'D771'
  trains:
    - 'G7072'
    - 'K5828'

  # 座位类型， 可选多个类型，越靠前优先级越高，例如：
  # - '二等座'
  # - '软卧'
  seat_type:
    - '二等座'
    - '硬座'

  # 乘车人， 可选多人乘车：
  # - name: '刘禅'
  #   ticket_type: '儿童票'
  # - name: '岳飞'
  #   ticket_type: '学生票'
  # - name: '金庸'
  #   ticket_type: '成人票'
  # - name: '周公'
  #   ticket_type: '残军票'
  # 注：学生票的乘车时间为每年的暑假6月1日至9月30日、寒假12月1日至3月31日，请人确认是否能购买学生票
  passengers:
    - name: '安于'
      ticket_type: '成人票'
    - name: '安宇'
      ticket_type: '成人票'


# 配置邮箱
email:
  # 是否开启邮箱提醒, False为关闭，True为开启
  flag: True

  # 连接邮箱的服务器名称
  host: 'smtp.qq.com'

  # 端口号
  port: 578

  # 发件邮箱号, 可以使用qq邮箱
  sender_account: '2916265470@qq.com'

  # 不是登陆密码，是客户端授权密码
  password: 'kvyjkfqodzasdgig'

  # 发件人
  sender: '12306购票'

  # 接收者
  receiver: '2916265470@qq.com'

  # 邮件主题
  subject: '12306订票成功通知'

  # 抢票成功提示信息, 即您要发送到邮箱的提示消息
  message: '恭喜您！已为您成功订票，请及时前往12306支付，订单将在30分钟后失效！'
